### ISSUE TITLE
Issue 1: Enhancement with a task list

### ISSUE THREAD

**Issue by maxild** [maxild/playground#1]
GitHub supports task lists. Task lists are lists with items marked as either [ ] or [x] (incomplete or complete). 

For example:

- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed

This means we can create issues which sort of contains other sub-issues that have to be completed in order for a Task-issue to be completed

- [ ] #6 
- [x] #4
- [ ] #2 

Off course this is a manual process to write 'x' into completed tasks in the list.
